name: strava_to_tweet

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  publish-data:
    runs-on: macos-latest
    env:
      STRAVA_ELEPHANT_SQL_DBNAME: ${{ secrets.STRAVA_ELEPHANT_SQL_DBNAME }}
      STRAVA_ELEPHANT_SQL_HOST: ${{ secrets.STRAVA_ELEPHANT_SQL_HOST }}
      STRAVA_ELEPHANT_SQL_USER: ${{ secrets.STRAVA_ELEPHANT_SQL_USER }}
      STRAVA_ELEPHANT_SQL_PASSWORD: ${{ secrets.STRAVA_ELEPHANT_SQL_PASSWORD }}
      STRAVA_TWITTER_CONSUMER_API_KEY: ${{ secrets.STRAVA_TWITTER_CONSUMER_API_KEY }}
      STRAVA_TWITTER_CONSUMER_API_SECRET: ${{ secrets.STRAVA_TWITTER_CONSUMER_API_SECRET }}
      STRAVA_TWITTER_ACCESS_TOKEN: ${{ secrets.STRAVA_TWITTER_ACCESS_TOKEN }}
      STRAVA_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.STRAVA_TWITTER_ACCESS_TOKEN_SECRET }}
      STRAVA_ID : ${{ secrets.STRAVA_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Install xml2 package
        run: Rscript -e 'install.packages("xml2", dependencies = TRUE)'
      - name: Install jsonlite package
        run: Rscript -e 'install.packages("jsonlite", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install ggplot2 package
        run: Rscript -e 'install.packages("ggplot2", dependencies = TRUE)'
      - name: Install gganimate package
        run: Rscript -e 'install.packages("gganimate", dependencies = TRUE)'
      - name: Install RPostgreSQL package
        run: Rscript -e 'install.packages("RPostgreSQL", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript get_activity_strava_save.R
        
